### ISSUE TITLE
[docs] : add a good README.md file to this repository

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [SohamRatnaparkhi/Fire-detection#1]
This project is based on Deep Learning. It is trained on 15000 images. It detects the presence of fire using the internal camera.

**Comment by Sarabjeet108** [comment]
Can I add a readme file after taking adaptations from the Contributor Covenant? https://www.contributor-covenant.org/

**Comment by SohamRatnaparkhi** [comment]
Okay sure.
